requireLogin(true);document.querySelector('#admin-name').textContent=session.user?.nome||'';const tabs=['eventos','midias','dizimos','intencoes'];document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tabs.forEach(t=>document.querySelector('#tab-'+t).hidden=t!==b.dataset.tab);loadTab(b.dataset.tab);});
function formMessage(form,text,error=false){const el=form.querySelector('.feedback');el.textContent=text;el.style.color=error?'crimson':'green';}
document.querySelector('#evento-form').onsubmit=async e=>{e.preventDefault();try{await api('/admin/eventos',{method:'POST',body:new FormData(e.target)});formMessage(e.target,'Evento salvo.');e.target.reset();loadEvents();}catch(x){formMessage(e.target,x.message,true);}};
document.querySelector('#midia-form').onsubmit=async e=>{e.preventDefault();try{await api('/admin/midias',{method:'POST',body:new FormData(e.target)});formMessage(e.target,'Mídia salva.');e.target.reset();loadMedia();}catch(x){formMessage(e.target,x.message,true);}};
async function loadEvents(){const data=await api('/eventos');document.querySelector('#eventos-lista').innerHTML=`<div class="grid">${data.map(x=>`<article class="card"><img src="${x.banner}" alt=""><div class="card-body"><h3>${escapeHtml(x.titulo)}</h3><p>${formatDate(x.data_inicio)} · ${escapeHtml(x.local)}</p><button class="danger" data-delete-event="${x.id}">Excluir</button></div></article>`).join('')}</div>`;}
async function loadMedia(){const data=await api('/midias');document.querySelector('#midias-lista').innerHTML=`<div class="grid">${data.map(x=>`<article class="card"><img src="${x.banner}" alt=""><div class="card-body"><h3>${escapeHtml(x.titulo)}</h3><p>${formatDate(x.data_evento)}</p><button class="danger" data-delete-media="${x.id}">Excluir</button></div></article>`).join('')}</div>`;}
async function loadDonations(){const data=await api('/admin/dizimos');document.querySelector('#dizimos-lista').innerHTML=`<div class="table-wrap"><table><tr><th>Nome</th><th>Valor</th><th>Data</th><th>Status</th><th>Ação</th></tr>${data.map(x=>`<tr><td>${escapeHtml(x.nome)}</td><td>R$ ${Number(x.valor).toFixed(2)}</td><td>${formatDate(x.data_pagamento)}</td><td>${x.status}</td><td><select data-status="${x.id}"><option value="pendente">Pendente</option><option value="aprovado">Aprovar</option><option value="rejeitado">Rejeitar</option></select></td></tr>`).join('')}</table></div>`;}
async function loadIntentions(){const data=await api('/admin/intencoes');document.querySelector('#intencoes-lista').innerHTML=`<div class="table-wrap"><table><tr><th>Nome</th><th>Descrição</th><th>Data</th></tr>${data.map(x=>`<tr><td>${escapeHtml(x.nome)}</td><td>${escapeHtml(x.descricao)}</td><td>${formatDate(x.data_missa)}</td></tr>`).join('')}</table></div>`;}
function loadTab(tab){if(tab==='eventos')loadEvents();if(tab==='midias')loadMedia();if(tab==='dizimos')loadDonations();if(tab==='intencoes')loadIntentions();}
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));}));
document.body.addEventListener('click',async e=>{
  if(e.target.dataset.deleteEvent){if(!confirm('Tem certeza que deseja remover este evento? Ele também deixará de aparecer no site público.'))return;try{await api('/admin/eventos/'+e.target.dataset.deleteEvent,{method:'DELETE'});await loadEvents();}catch(error){alert(error.message);}}
  if(e.target.dataset.deleteMedia){if(!confirm('Tem certeza que deseja remover esta mídia?'))return;try{await api('/admin/midias/'+e.target.dataset.deleteMedia,{method:'DELETE'});await loadMedia();}catch(error){alert(error.message);}}
});
document.body.addEventListener('change',async e=>{if(e.target.dataset.status){try{await api('/admin/dizimos/'+e.target.dataset.status,{method:'PUT',body:JSON.stringify({status:e.target.value})});}catch(error){alert(error.message);}}});
loadEvents();
